# Copyright (C) 2020 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

name: Github Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc

      - name: Create index
        uses: DamianReeves/write-file-action
        with:
          path: ./target/doc/index.html
          contents: |
            <meta http-equiv="refresh" content="0; url=soap/index.html">
            <a href="soap/index.html">Redirect</a>
          write-mode: overwrite

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
